### ISSUE TITLE
The `backend` configuration key is NOT supported anymore.") ValueError: Can not train an empty pipeline. Make sure to specify a proper pipeline in the configuration using the `pipeline` key.

### ISSUE THREAD

**Issue by artiberde27** [bhavaniravi/rasa-site-bot#1]
Hi @bhavaniravi ,
Thanks for you-tube video tutorial it is very good for basic understanding.

I am getting below error when in run **python3 -m rasa_nlu.train -c config_mitie.json** this command.I had download total_word_feature_extractor.dat as instructed in installation steps.

```
INFO:rasa_nlu.converters:Training data format at data/sitebot-data.json is rasa_nlu
INFO:rasa_nlu.training_data:Training data stats: 
	- intent examples: 36 (6 distinct intents)
	- found intents: 'affirm', 'event-request', 'event-time', 'goodbye', 'greet', 'intro'
	- entity examples: 15 (5 distinct entities)
	- found entities: 'day', 'event_name', 'place', 'relative-time', 'time'

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/site-packages/rasa_nlu/train.py", line 125, in <module>
    do_train(config)
  File "/usr/local/lib/python3.5/site-packages/rasa_nlu/train.py", line 114, in do_train
    interpreter = trainer.train(training_data)
  File "/usr/local/lib/python3.5/site-packages/rasa_nlu/model.py", line 149, in train
    components.validate_arguments(self.pipeline, context)
  File "/usr/local/lib/python3.5/site-packages/rasa_nlu/components.py", line 107, in validate_arguments
    "The `backend` configuration key is NOT supported anymore.")
ValueError: Can not train an empty pipeline. Make sure to specify a proper pipeline in the configuration using the `pipeline` key.The `backend` configuration key is NOT supported anymore.





```

**Comment by rasaLearner** [comment]
am having same issue any solution to this ?

**Comment by bhavaniravi** [comment]
@vanipolnedi can you post your config json and error message log here

**Comment by vanipolnedi** [comment]
@bhavaniravi  i resolved that issue but now i am getting another issue 
exception is : exception
'intent'

i am using config_spacy.json

 in app.py , my chat fn is:
def chat():
    """
    chat end point that performs NLU using rasa.ai
    and constructs response from response.py
    """
    try:
        response = requests.get("http://10.40.20.81:1234",params={"q":request.form["text"]})
        #print (response)
        s=jsonpickle.encode(response)

        #print (type(s))
        json_acceptable_string = s.replace("'", "\"")
        d = json.loads(json_acceptable_string)
		
        # print (".......")
        # for key, value in d.items():
            # print(key, value)
            # print ("\n")
        intent = d["intent"]
        print (intent)
        entities = format_entities(d["entities"])
        print (entities)
        if intent == "event-request":
            response_text = get_event(entities["day"],entities["time"],entities["place"])
        else:
            response_text = get_random_response(intent)
        return jsonify({"status":"success","response":response_text})
    except Exception as e:
        print ("exception")
        print (e)
        return jsonify({"status":"success","response":"Sorry I am not trained to do that yet..."})



and for every msg ,it is giving output as Sorry I am not trained to do that yet...

**Comment by bhavaniravi** [comment]
https://youtu.be/ojuq0vBIA-g

**Comment by nadabou** [comment]
I am encountering the same error when trying to train a model via the HTTP API:
![image](https://user-images.githubusercontent.com/29257680/52573927-74cb8380-2e1b-11e9-9333-3616bc181099.png)

![image](https://user-images.githubusercontent.com/29257680/52574132-e1df1900-2e1b-11e9-8ca6-a2237a68367f.png)


But I already have the following nlu_config.yml file:

`language: "en"
pipeline: "spacy_sklearn"`

Was anyone able to solve this ?

**Comment by ajinkyaghodake123** [comment]
File "c:\users\ajinkya\anaconda3\envs\env1\lib\site-packages\rasa\nlu\train.py", line 86, in train
    interpreter = trainer.train(training_data, **kwargs)
  File "c:\users\ajinkya\anaconda3\envs\env1\lib\site-packages\rasa\nlu\model.py", line 180, in train
    components.validate_arguments(self.pipeline, context)
  File "c:\users\ajinkya\anaconda3\envs\env1\lib\site-packages\rasa\nlu\components.py", line 66, in validate_arguments
    "Can not train an empty pipeline. "
ValueError: Can not train an empty pipeline. Make sure to specify a proper pipeline in the configuration using the `pipeline` key.The `backend` configuration key is NOT supported anymore.


I am getting this error and interesting this is i am not using "backend" anywhere in my code.
{
  "pipeline":"spacy_sklearn",
  "path":"./models/nlu",
  "data":"./data/data.json"
} 

This is my config.json.
Could you please help me here.
