### ISSUE TITLE
Error when running app.py

### ISSUE THREAD

**Issue by mandelakibiriti** [bhavaniravi/rasa-site-bot#2]
The script throws an error when running `python app.py`

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from models import *
  File "/home/ubuntu/Projects/rasa-site-bot/bot-application/models.py", line 3, in <module>
    from urllib import quote_plus as urlquote
_ImportError: cannot import name 'quote_plus'_

**Comment by bhavaniravi** [comment]
if you are using pytho3 change the line to 
`from urllib.parse import quote_plus as urlquote`

**Comment by mandelakibiriti** [comment]
1. I changed the line as suggested and an Attribute error from models.py emerged
`Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from models import *
  File "/home/ubuntu/Projects/rasa-site-bot/bot-application/models.py", line 42, in <module>
    admin.add_view(MyModelView(Event, db.session))
  File "/home/ubuntu/Projects/rasa-site-bot/bot-application/models.py", line 35, in __init__
    for k, v in kwargs.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'`

2. I changed `for k, v in kwargs.iteritems()` to `for k, v in kwargs.items()` in line 35, models.py

3. I ran app.py and it worked however the bot doesn't output the intended response when I begin the chat
![image](https://user-images.githubusercontent.com/32020107/44617615-650cb280-a86e-11e8-9bb0-5f312ff53757.png)
![image](https://user-images.githubusercontent.com/32020107/44617640-ef551680-a86e-11e8-86c1-60da8b2a4193.png)

I'm I doing something wrong?

**Comment by harshitazilen** [comment]
@mandelakibiriti , You need to start rasa NLU server. 

See line 51 in bot-application/App.py file. 
`response = requests.get("http://localhost:5000/parse",params={"q":request.form["text"]})`

It requests Rasa NLU server and later will show its response in the webpage.

So start Rasa NLU server and it will start responding.
