### ISSUE TITLE
Bot Response Error

### ISSUE THREAD

**Issue by GopalMadhaiyan** [bhavaniravi/rasa-site-bot#4]
home/testing/.local/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: builtins.DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.

**Comment by bhavaniravi** [comment]
@GopalMadhaiyan Can you post in Detail what are were you trying to. Also I have updated the project with instructions w.r. to latest version. You can try with the new setup.

**Comment by GopalMadhaiyan** [comment]
Dear Bhavaniravi,
Yeah Thanks.. I am java developer.. Now only I started to learn Python with
AI chatbot.. I update you soon..

**Comment by GopalMadhaiyan** [comment]
Dear Bhavaniravi,
Now Working fine. Thanks.
